franchise_path={
    'franchise_mgmt_menu_path':'/html/body/div/div/aside/section[2]/div[2]/button/div',
    'franchise_acc_menu_path':'/html/body/div/div/aside/section[2]/div[2]/div/div[1]/a/span',
    'search_box_name':'code',
    'name_search_result_path':'/html/body/div/div/div[1]/div/div/div/div/form/table/tbody/tr/td[1]',
    'email_search_result_path':'/html/body/div/div/div[1]/div/div/div/div/form/table/tbody/tr/td[2]',
    'entity_name_search_result_path':'/html/body/div/div/div[1]/div/div/div/div/form/table/tbody/tr/td[3]',

#active_inactive_listing_action

    'list_three_dots_action_btn_pth':'/html/body/div/div/div[1]/div/div/div/div/form/table/tbody/tr[1]/td[6]/div/button',
    'list_set_as_inactive':'/html/body/div[2]/div/div',
    'yes_set_as_in_active':'/html/body/div/div/div[3]/div[2]/div[2]/div[2]/button[2]',

    'check_status_path':'/html/body/div/div/div[1]/div/div/div/div/form/table/tbody/tr[1]/td[5]/div',

    'list_set_as_active':'/html/body/div[2]/div/div',
    'yes_set_as_active':'/html/body/div/div/div[3]/div[2]/div[2]/div[2]/button[2]',

    'row_per_page_select_box_path':'/html/body/div/div/div[1]/div/div/div/div/form/table/tfoot/tr/td/div/div[1]/select',
    '10_row_per_page_path':'/html/body/div/div/div[1]/div/div[1]/div/div/form/table/tfoot/tr/td/div/div[1]/select/option[1]',
    '20_row_per_page_path':'/html/body/div/div/div[1]/div/div[1]/div/div/form/table/tfoot/tr/td/div/div[1]/select/option[2]',
    '50_row_per_page_path':'/html/body/div/div/div[1]/div/div[1]/div/div/form/table/tfoot/tr/td/div/div[1]/select/option[3]',

    'next_page_btn_path':'/html/body/div/div/div[1]/div/div[1]/div/div/form/table/tfoot/tr/td/div/div[2]/div[1]',
    'prev_page_btn_path':'/html/body/div/div/div[1]/div/div/div/div/form/table/tfoot/tr/td/div/div[2]/div[3]',
    'page_1_btn_path':'/html/body/div/div/div[1]/div/div/div/div/form/table/tfoot/tr/td/div/div[2]/div[2]/div[1]',
    'page_2_btn_path':'/html/body/div/div/div[1]/div/div/div/div/form/table/tfoot/tr/td/div/div[2]/div[2]/div[2]',

    'add_new_franchise_btn_path':'/html/body/div/div/div[1]/div/div/div/div/form/section/div/button',
    'email_address_name':'email',
    'franchise_name':'name',
    'add_entity_btn_path':'/html/body/div/div/div[1]/div/div/div/div/form/div[2]/div/div[1]/section[2]/div/button',
    'delete_entity_btn':'/html/body/div/div/div[1]/div/div[1]/div/div/form/div[2]/div/div[1]/section[2]/div/div[2]/button',
    'entity_name':'franchiseEntities.0.title',
    'uen_name':'franchiseEntities.0.entityNo',
    'outlet_owned_select_box_path':'/html/body/div/div/div[1]/div/div[1]/div/div/form/div[2]/div/div[1]/section[2]/div/div/div[2]/div[3]/fieldset/button',
    'select_outlet_name_check_box_path':'/html/body/div/div/div[1]/div/div[1]/div/div/form/div[2]/div/div[1]/section[2]/div/div/div[2]/div[4]/div/ul/li[4]/input',
    'updated_outlet_owned_value_path':'/html/body/div/div/div[1]/div/div/div/div/form/div[2]/div/div[1]/section[2]/div/div/div[2]/div[4]/div/ul/li[3]/input',
    'rule_1_checkbox':'/html/body/div/div/div[1]/div/div/div/div/form/div[2]/div/div[1]/section[3]/div/div[1]/div/fieldset/div/button',
    'rule_2_checkbox':'/html/body/div/div/div[1]/div/div/div/div/form/div[2]/div/div[1]/section[3]/div/div[2]/div/fieldset/div/button',
    'acc_no_name':'accountNo',
    'acc_holder_name':'accountHolderName',
    'bank_name':'bankName',
    'sort_code_name':'sortCode',
    'bill_name':'billingName',
    'bill_email_name':'billingEmail',
    'country_code_btn_path':'/html/body/div/div/div[1]/div/div[1]/div/div/form/div[2]/div/div[1]/section[5]/div/div[3]/fieldset/button',
    'bill_mobile_no_name':'billingMobile',
    'company_name':'companyName',
    'country_dropdown_path':'/html/body/div/div/div[1]/div/div[1]/div/div/form/div[2]/div/div[1]/section[5]/div/div[5]/fieldset/button',
    'selected_outlet_path':'/html/body/div/div/div[1]/div/div[1]/div/div/form/div[2]/div/div[1]/section[5]/div/div[5]/fieldset/select/option[8]',
    'updated_outlet_path':"/html/body/div/div/div[1]/div/div[1]/div/div/form/div[2]/div/div[1]/section[5]/div/div[5]/fieldset/select/option[7]",
    'postal_or_zip_code_name':'postalCode',
    'company_address_path':'/html/body/div/div/div[1]/div/div[1]/div/div/form/div[2]/div/div[1]/section[5]/div/div[7]/fieldset/div/textarea',
    'create_btn_path':'/html/body/div/div/div[1]/div/div/div/div/form/footer/div/button',


    'invalid_email_err_msg_path':'/html/body/div/div/div[1]/div/div/div/div/form/div[2]/div/div[1]/section[1]/div[1]/p',
    'req_email_err_msg_path':'/html/body/div/div/div[1]/div/div/div/div/form/div[2]/div/div[1]/section[1]/div[1]/p',
    'req_franchise_name_err_msg_path':'/html/body/div/div/div[1]/div/div/div/div/form/div[2]/div/div[1]/section[1]/div[2]/p',
    'req_entity_name_err_msg_path':'/html/body/div/div/div[1]/div/div[1]/div/div/form/div[2]/div/div[1]/section[2]/div/div/div[2]/div[1]/p',
    'req_uen_err_msg_path':'/html/body/div/div/div[1]/div/div[1]/div/div/form/div[2]/div/div[1]/section[2]/div/div/div[2]/div[2]/p',
    'req_outlet_owned_err_msg_path':'/html/body/div/div/div[1]/div/div/div/div/form/div[2]/div/div[1]/section[2]/div/div/div[2]/div[3]/p',
    'req_acc_no_err_msg_path':'/html/body/div/div/div[1]/div/div/div/div/form/div[2]/div/div[1]/section[4]/div/div[1]/p',
    'req_acc_holder_name_err_msg_path':'/html/body/div/div/div[1]/div/div/div/div/form/div[2]/div/div[1]/section[4]/div/div[2]/p',
    'req_bank_name_err_msg_path':'/html/body/div/div/div[1]/div/div/div/div/form/div[2]/div/div[1]/section[4]/div/div[3]/p',
    'req_sort_code_err_msg_path':'/html/body/div/div/div[1]/div/div/div/div/form/div[2]/div/div[1]/section[4]/div/div[4]/p',
    'req_billing_name_err_msg_path':'/html/body/div/div/div[1]/div/div/div/div/form/div[2]/div/div[1]/section[5]/div/div[1]/p',
    'invalid_billing_email_err_msg_path':'/html/body/div/div/div[1]/div/div[1]/div/div/form/div[2]/div/div[1]/section[5]/div/div[2]/p',
    'req_billing_email_err_msg_path':'/html/body/div/div/div[1]/div/div/div/div/form/div[2]/div/div[1]/section[5]/div/div[2]/p',
    'req_billing_mobile_err_msg_path':'/html/body/div/div/div[1]/div/div/div/div/form/div[2]/div/div[1]/section[5]/div/div[3]/p',
    'req_company_name_err_msg_path':'/html/body/div/div/div[1]/div/div/div/div/form/div[2]/div/div[1]/section[5]/div/div[4]/p',
    'req_postal_code_err_msg_path':'/html/body/div/div/div[1]/div/div/div/div/form/div[2]/div/div[1]/section[5]/div/div[6]/p',
    'req_company_address_err_msg_path':'/html/body/div/div/div[1]/div/div/div/div/form/div[2]/div/div[1]/section[5]/div/div[7]/p',

    'edit_btn_path':'/html/body/div/div/div[1]/div/div[1]/div/div/form/table/tbody/tr[1]/td[6]/div/span',

    'more_action_btn_path':'/html/body/div[1]/div/div[1]/div/div/div/div/form/header/div[2]/button/p/span[1]',
    'more_action_inactive_btn_path':'/html/body/div[2]/div/ul/li',
    'more_action_active_btn_path':'/html/body/div[2]/div/ul/li',
}